name: bugget_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.2.1
  amplify_api: ^1.2.0
  amplify_auth_cognito: ^1.2.1
  amplify_authenticator: ^1.2.1
  go_router: ^10.0.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true


